<?php
namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ThreadTests extends TestCase
{
    use RefreshDatabase;
    protected $thread;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    /** @test */
    public function a_user_can_browse_threads()
    {
        // when user visit a /threads route
        $response = $this->get('/threads');

        // when user visit a index page, should see a thread's title
        $response->assertSee($this->thread->title);
    }

    /** @test */
    public function a_user_can_view_a_single_thread()
    {
        // when user visit a /threads/{thread->id} route
        $response = $this->get('/threads/' . $this->thread->id);

        // when user visit a index page, should see a single thread's title
        $response->assertSee($this->thread->title);
    }

    /** @test */
    public function a_thread_can_have_replies_and_a_user_can_see_all_of_those_replies(){
        $reply = factory('App\Reply')
            ->create(['thread_id' => $this->thread->id]);
        $this->get('/threads/' . $this->thread->id)
            ->assertSee($reply->body);
    }

    /** @test */
    public function a_thread_belongs_to_a_creator()
    {
        $this->assertInstanceOf('App\User', $this->thread->creator);
    }

    /** @test */
    public function a_thread_can_persist_a_new_reply()
    {
        $this->thread->addReply([
           'body' => 'foobar',
           'user_id' => 1
        ]);

        $this->assertCount(1, $this->thread->replies);
    }
}
