<?php
namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ThreadTests extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    /** @test */
    public function a_user_can_browse_threads()
    {
        // when user visit a /threads route
        $response = $this->get('/threads');

        // when user visit a index page, should see a thread's title
        $response->assertSee($this->thread->title);
    }

    /** @test */
    public function a_user_can_view_a_single_thread()
    {
        // when user visit a /threads/{thread->id} route
        $response = $this->get('/threads/' . $this->thread->id);

        // when user visit a index page, should see a single thread's title
        $response->assertSee($this->thread->title);
    }

    /** @test */
    public function a_thread_can_have_replies(){
        $reply = factory('App\Reply')
            ->create(['thread_id' => $this->thread->id]);
        $this->get('/threads/' . $this->thread->id)
            ->assertSee($reply->body);
    }
}
